version: '3.8'

services:
  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-service
    env_file:
      - ../../.env
    environment:
      - FLASK_APP=order_service.py
      - FLASK_ENV=development
    ports:
      - "8003:8003"
    volumes:
      - .:/app
      - ../../.env:/app/.env
    networks:
      - esd_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  esd_network:
    external: true 