version: '3.8'

services:
  payment-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-service
    env_file:
      - ../../.env
    environment:
      - FLASK_APP=payment_service.py
      - FLASK_ENV=development
    ports:
      - "8002:8002"
    volumes:
      - .:/app
      - ../../.env:/app/.env
    networks:
      esd_network:
        aliases:
          - payment-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/user/email/test@example.com"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  esd_network:
    external: true