version: '3.8'

services:
  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-service
    environment:
      - FLASK_APP=order_service.py
      - FLASK_ENV=development
      - MONGO_URI=mongodb+srv://elijahtan2023:TXFgo2T6kEvD9pPh@esd.t8r4e.mongodb.net/esd
    ports:
      - "8003:8003"
    networks:
      - user_service_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  user_service_network:
    external: true 