version: '3.8'

services:
  ticket-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticket-service
    environment:
      - MONGO_URI=mongodb+srv://elijahtan2023:TXFgo2T6kEvD9pPh@esd.t8r4e.mongodb.net/esd
      - SECRET_KEY=supersecurekey
      - GOOGLE_CLIENT_ID=603980424659-jiqs010nggvjmn6ve8c243nfral3q5a7.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - FRONTEND_URL=http://localhost:5173
      - FLASK_APP=app.py
      - FLASK_ENV=development
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    networks:
      esd_network:
        aliases:
          - ticket-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/user/email/test@example.com"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  esd_network:
    external: true