version: '3.8'

services:
  ticket-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticket-service
    env_file:
      - ../../.env
    environment:
      - FLASK_APP=ticket_service.py
      - FLASK_ENV=development
    ports:
      - "5001:5001"
    volumes:
      - .:/app
      - ../../.env:/app/.env
    networks:
      esd_network:
        aliases:
          - ticket-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/user/email/test@example.com"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  esd_network:
    external: true