version: '3.8'

services:
  kong:
    image: kong:latest
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_DECLARATIVE_CONFIG: /opt/kong/kong.yml
    ports:
      - "8000:8000"  # Proxy listener
      - "8443:8443"  # Proxy listener (SSL)
      - "8001:8001"  # Admin API listener
      - "8444:8444"  # Admin API listener (SSL)
    volumes:
      - ./kong.yml:/opt/kong/kong.yml
    networks:
      - user_service_network  # Connect to user service network
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10

networks:
  user_service_network:
    external: true  # Use the existing network from user service
