
services:
  refund-user:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: refund-user
    environment:
      - FLASK_APP=refund_user.py
      - FLASK_ENV=development
      - USER_SERVICE_URL=http://user-service:5003
      - TICKET_SERVICE_URL=http://ticket-service:5001
      - ORDER_SERVICE_URL=http://order-service:8003
      - PAYMENT_SERVICE_URL=http://payment-service:8002
      - RABBITMQ_URL=amqp://host.docker.internal:5672
    ports:
      - "5004:5004"
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      esd_network:
        aliases:
          - refund-user

networks:
  esd_network:
    external: true
